### ISSUE TITLE
Error executing lua: ...azy/multiple-session.nvim/lua/multiple-session/utils.lua:5: attempt to index upvalue 'core' (a boolean value)

### ISSUE THREAD

**Issue by CleoMenezesJr** [niuiic/multiple-session.nvim#2]
This error appears every time I execute commands to save, restore and delete sessions.
![Screenshot from 2023-10-22 22-36-20](https://github.com/niuiic/multiple-session.nvim/assets/54215258/0ed6668e-3058-4376-b925-655cae34ef65)

**Comment by niuiic** [comment]
You may have another module named “core” except “niuiic/core.nvim”

Or check your neovim version, it should work fine in v0.8-v0.10

**Comment by CleoMenezesJr** [comment]
I'm using NVChad, and apparently they have a module called core. Any workaround you suggest?

**Comment by niuiic** [comment]
Emm, you may use another session manager instead. Check awesome neovim list, and there are multiple this kind of plugins.
